# Generated by Django 5.2.4 on 2025-09-12 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGrabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grabado',
            fields=[
                ('of_numero', models.AutoField(primary_key=True, serialize=False, verbose_name='OF.')),
                ('of_referencia', models.CharField(max_length=100, unique=True, verbose_name='OF. Referencia')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cliente', models.CharField(max_length=255, verbose_name='Cliente')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_programacion', models.DateField(verbose_name='Fecha de Programación')),
                ('ubicacion', models.CharField(blank=True, max_length=255, verbose_name='Ubicación')),
                ('ubicacion_carpeta', models.CharField(blank=True, max_length=255, verbose_name='Ubicación Carpeta')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grabados.maquina', verbose_name='Máquina')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grabados.proceso', verbose_name='Proceso')),
                ('tipo_grabado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grabados.tipograbado', verbose_name='Tipo de Grabado')),
            ],
            options={
                'verbose_name': 'Grabado',
                'verbose_name_plural': 'Grabados',
                'ordering': ['-fecha_programacion'],
            },
        ),
    ]
