# Generated by Django 5.2.5 on 2025-10-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grabado',
            name='of_numero',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='OF.'),
        ),
        migrations.AlterField(
            model_name='grabado',
            name='of_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OF. Referencia'),
        ),
    ]
